#!/bin/bash

# Shared pre-commit hook.
# Lints using Black and Flake8
# Runs tests in all packages using pytest
# Install using spynl-cli dev install-git-hooks

set -euf -o pipefail

PROJECT_ROOT=$(git rev-parse --show-toplevel)

python -m black -S --check $PROJECT_ROOT
python -m flake8 $PROJECT_ROOT
spynl-cli dev test --non-interactive
